name: settle
services:
  database:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./.local/db-data/:/var/lib/postgresql/data/
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "25432:5432"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 25433:80
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - postgres-network
    volumes:
      - ./.local/pgadmin-data/:/var/lib/pgadmin

  s3:
    image: adobe/s3mock:latest
    ports:
      - "9090:9090"
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIALBUCKETS=bucket
      - COM_ADOBE_TESTING_S3MOCK_STORE_RETAINFILESONEXIT=true
      - COM_ADOBE_TESTING_S3MOCK_STORE_ROOT=/data
    volumes:
      - ./.s3data:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "21025:1025"
      - "28025:8025"

networks:
  postgres-network:
    driver: bridge
